In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
from sklearn.linear_model import LogisticRegression

In [2]:
# Import the data 
bank_df = pd.read_csv('./data/bank_full_w_dummy_vars.csv')
bank_df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... job_unknown                   \
0  unknown    5  ...                            0   
1  unknown    5  ...                            0   
2  unknown    5  ...                            0   
3  unknown    5  ...                            0   
4  unknown    5  ...                            1   

   job_retired                   job_services                  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   job_self_employed             job_unemployed                \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

  job_maid                     job_student                   \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   

   married                       single                        \
0                             1                             0   
1                             0                             1   
2                             1                             0   
3                             1                             0   
4                             0                             1   

   divorced                      
0                             0  
1                             1  
2                             0  
3                             0  
4                             1  

[5 rows x 37 columns]

In [6]:
for col in bank_df:
    print(col)
    print(bank_df[col].unique())

age
[58 44 33 47 35 28 42 43 41 29 53 57 51 45 60 56 32 25 40 39 52 46 36 49
 59 37 50 54 55 48 24 38 31 30 27 34 23 26 61 22 21 20 66 62 83 75 67 70
 65 68 64 69 72 71 19 76 85 63 90 82 73 74 78 80 94 79 77 86 95 81 18 89
 84 87 92 93 88]
job
['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']
marital
['married' 'single' 'divorced']
education
['tertiary' 'secondary' 'unknown' 'primary']
default
['no' 'yes']
balance
[ 2143    29     2 ...  8205 14204 16353]
housing
['yes' 'no']
loan
['no' 'yes']
contact
['unknown' 'cellular' 'telephone']
day
[ 5  6  7  8  9 12 13 14 15 16 19 20 21 23 26 27 28 29 30  2  3  4 11 17
 18 24 25  1 10 22 31]
month
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
duration
[ 261  151   76 ... 1298 1246 1556]
campaign
[ 1  2  3  5  4  6  7  8  9 10 11 12 13 19 14 24 16 32 18 22 15 17 25 21
 43 51 63 41 26 28 55 50 38 23 20 29 31 37 30 46 27

In [7]:
bank_df = bank_df.dropna()

In [12]:
bank_df.shape

(45211, 37)

In [19]:
bank_df = bank_df[bank_df.education != "unknown"]
bank_df.shape

(43193, 37)

In [20]:
bank_df = bank_df[bank_df.job != "unknown"]
bank_df.shape

(43193, 37)

In [ ]:
bank_df['y'].value_counts()

In [121]:
success = bank_df[bank_df.y == "yes"]
success.shape

(5021, 37)

In [122]:
fail = bank_df[bank_df.y != "yes"]
fail = fail.sample(n=5021)
fail.shape

(5021, 37)

In [123]:
bank_df = pd.concat([success, fail])
bank_df

age         job  marital  education default  balance housing loan  \
83      59      admin.  married  secondary      no     2343     yes   no   
86      56      admin.  married  secondary      no       45      no   no   
87      41  technician  married  secondary      no     1270     yes   no   
129     55    services  married  secondary      no     2476     yes   no   
168     54      admin.  married   tertiary      no      184      no   no   
...    ...         ...      ...        ...     ...      ...     ...  ...   
25077   32    services   single  secondary      no       48     yes  yes   
31676   38  unemployed  married   tertiary      no     2012      no   no   
35048   41  management  married   tertiary      no     2470     yes   no   
25270   39  unemployed  married   tertiary      no     1108     yes   no   
12193   38    services  married  secondary      no      503      no   no   

        contact  day  ... job_unknown                   \
83      unknown    5  ...                            0   
86      unknown    5  ...                            0   
87      unknown    5  ...                            0   
129     unknown    5  ...                            0   
168     unknown    5  ...                            0   
...         ...  ...  ...                          ...   
25077  cellular   18  ...                            0   
31676  cellular    7  ...                            0   
35048  cellular    6  ...                            0   
25270  cellular   18  ...                            0   
12193   unknown   20  ...                            0   

       job_retired                   job_services                  \
83                                0                             0   
86                                0                             0   
87                                0                             0   
129                               0                             1   
168                               0                             0   
...                             ...                           ...   
25077                             0                             1   
31676                             0                             0   
35048                             0                             0   
25270                             0                             0   
12193                             0                             1   

       job_self_employed             job_unemployed                \
83                                0                             0   
86                                0                             0   
87                                0                             0   
129                               0                             0   
168                               0                             0   
...                             ...                           ...   
25077                             0                             0   
31676                             0                             1   
35048                             0                             0   
25270                             0                             1   
12193                             0                             0   

      job_maid                     job_student                   \
83                               0                            0   
86                               0                            0   
87                               0                            0   
129                              0                            0   
168                              0                            0   
...                            ...                          ...   
25077                            0                            0   
31676                            0                            0   
35048                            0                            0   
25270                            0                            0   
12

In [124]:
for col in bank_df:
    print(col)
    print(bank_df[col].unique())

age
[59 56 41 55 54 42 60 37 34 28 30 36 45 53 38 29 46 31 39 35 32 49 43 26
 40 33 24 23 48 52 57 51 50 44 27 47 25 58 61 62 68 75 22 69 64 66 85 72
 90 67 71 21 63 73 74 65 83 79 70 76 77 19 20 78 95 82 18 86 84 87 81 80
 88]
job
['admin.' 'technician' 'services' 'management' 'retired' 'unemployed'
 'blue-collar' 'entrepreneur' 'housemaid' 'self-employed' 'student']
marital
['married' 'single' 'divorced']
education
['secondary' 'tertiary' 'primary']
default
['no' 'yes']
balance
[2343   45 1270 ... 7858 1576 2012]
housing
['yes' 'no']
loan
['no' 'yes']
contact
['unknown' 'cellular' 'telephone']
day
[ 5  6  7  8  9 12 13 14 15 16 19 20 21 23 26 27 28 29 30  2  3  4 11 17
 18 24  1 10 22 25 31]
month
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
duration
[1042 1467 1389 ... 1687  936 1220]
campaign
[ 1  2  3  4  5  6 32  8 11  7 10 15 12 14  9 17 13 24 29 16 21 20 26 19
 25 35 51 18 22 27 31 30 28 23 33 38]
pdays
[ -1 166  91 143 147 170 104 150 171 126 182 1

In [125]:
test_df = bank_df[["y", 'age', 'marital', 'job', 'loan', 'education']]
test_df

y  age  marital         job loan  education
83     yes   59  married      admin.   no  secondary
86     yes   56  married      admin.   no  secondary
87     yes   41  married  technician   no  secondary
129    yes   55  married    services   no  secondary
168    yes   54  married      admin.   no   tertiary
...    ...  ...      ...         ...  ...        ...
25077   no   32   single    services  yes  secondary
31676   no   38  married  unemployed   no   tertiary
35048   no   41  married  management   no   tertiary
25270   no   39  married  unemployed   no   tertiary
12193   no   38  married    services   no  secondary

[10042 rows x 6 columns]

In [126]:
test_df['job'] = test_df['job'].replace(["management", 'technician', 'entrepreneur',
                 'blue-collar', 'admin.', 'services', 'self-employed', 'housemaid'],
                "employed")

C:\Users\lokma\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [127]:
for col in test_df:
    print(col)
    print(test_df[col].unique())

y
['yes' 'no']
age
[59 56 41 55 54 42 60 37 34 28 30 36 45 53 38 29 46 31 39 35 32 49 43 26
 40 33 24 23 48 52 57 51 50 44 27 47 25 58 61 62 68 75 22 69 64 66 85 72
 90 67 71 21 63 73 74 65 83 79 70 76 77 19 20 78 95 82 18 86 84 87 81 80
 88]
marital
['married' 'single' 'divorced']
job
['employed' 'retired' 'unemployed' 'student']
loan
['no' 'yes']
education
['secondary' 'tertiary' 'primary']


In [128]:
test_df = pd.get_dummies(test_df)
test_df.head()

age  y_no  y_yes  marital_divorced  marital_married  marital_single  \
83    59     0      1                 0                1               0   
86    56     0      1                 0                1               0   
87    41     0      1                 0                1               0   
129   55     0      1                 0                1               0   
168   54     0      1                 0                1               0   

     job_employed  job_retired  job_student  job_unemployed  loan_no  \
83              1            0            0               0        1   
86              1            0            0               0        1   
87              1            0            0               0        1   
129             1            0            0               0        1   
168             1            0            0               0        1   

     loan_yes  education_primary  education_secondary  education_tertiary  
83          0                  0                    1                   0  
86          0                  0                    1                   0  
87          0                  0                    1                   0  
129         0                  0                    1                   0  
168         0                  0                    0                   1

In [132]:
X = test_df.ix[:,(0, 3, 4, 6, 7, 8, 11, 12, 13)].values
y = test_df.iloc[:,1].values

C:\Users\lokma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\lokma\Anaconda3\lib\site-packages\pandas\core\indexing.py:961: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return getattr(section, self.name)[new_key]


In [133]:
# Fitting the data with logistic regression model
logReg = LogisticRegression()
clf = logReg.fit(X, y)

C:\Users\lokma\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [134]:
# Predict with input data
new_user = [[30, 0, 0, 0, 1, 0, 1, 0, 1]]
y_pred = logReg.predict(new_user)
y_pred

array([0], dtype=uint8)

In [136]:
# Predict the probability
new_user = [[40, 0, 0, 0, 0, 1, 0, 1, 0]]
clf.predict_proba(new_user)

array([[0.67926374, 0.32073626]])

In [137]:
clf.score(X, y)

0.5948018323043218

In [138]:
# Predict the probability
new_user = [[50, 0, 1, 1, 0, 0, 0, 0, 0]]
clf.predict_proba(new_user)

array([[0.55594631, 0.44405369]])

In [139]:
clf.coef_

array([[-0.01015271,  0.26076841,  0.41489702,  0.41416552, -0.49510469,
        -0.55737445,  0.63822484,  0.7592458 ,  0.37757008]])

In [140]:
# Predicting the test set results
y_hat = logReg.predict(X)

In [141]:
# Create confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_hat, labels=[0, 1])

array([[3114, 1907],
       [2162, 2859]], dtype=int64)

### Package the Model into a Pickle Object

In [143]:
# Import pickle to pacakge the mdoel
import pickle

In [144]:
# Saving model to disk
pickle.dump(logReg, open("./model/reg_model.pkl", "wb"))

In [146]:
#Loading mdoel to compare the results
model = pickle.load(open("./model/reg_model.pkl", "rb"))
print(model.predict_proba([[55, 0, 1, 0, 0, 0, 1, 0, 1]]))

[[0.41918022 0.58081978]]


In [147]:
# Check the model score
model.score(X, y)

0.5948018323043218